# application.yml
spring:
  profiles:
    active: dev-local
  application:
    name: user-svc
  #日期格式化配置
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss #如果使用字符串表示，用这行设置格式
    timezone: GMT+8
    serialization:
      write-dates-as-timestamps: true #使用时间戳，使用数值timestamp表示日期
  mvc:
    throw-exception-if-no-handler-found: true #解决404异常拦截器拦截不到问题
  resources:
    add-mappings: false

server:
  tomcat:
    accept-count: 400
    uri-encoding: UTF-8
    min-spare-threads: 25
    max-threads: 400
    connection-timeout: 20000 # 超时时间20秒

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


auth:
  except:
    - /swagger-resources.*
    - /v2/api-docs.*
    - /error