management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8000
  tomcat:
    accesslog:
      buffered: true
      directory: /Volumes/Any/log/tomcat/dev-gateway
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log

spring:
  redis:
    database: 1
    host: i.docker.com
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）默认是2000
    timeout: 5000
  cloud:
    nacos:
      discovery:
        server-addr: i.docker.com:8848